logging:
  level:
    root: info
application:
  s3:
    endpoint: localhost
    port: 9000
    secure: false
    credentials:
      accessKey: root
      secretKey: password
    buckets:
      notesBucketName: notes
  datasources:
    postgresql:
      jdbcUrl: jdbc:postgresql://localhost:5432/notepirate
      username: root
      password: password
      driverClassName: org.postgresql.Driver
